version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: nginx_ft_transcendence
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: fastify_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./backend/srcs:/app/srcs
      - ./backend/database:/app/database
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: frontend_transcendence
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend

      
